name: Test
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '^1.22.3'
      id: go

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create build output directory
      run: mkdir build

    - name: Build
      run: go build -a -v -o build .

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: gateway
        path: build
